# Generated by Django 3.1.3 on 2020-11-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'insertar un numero mayor que 0'}, max_digits=10),
        ),
    ]
