# Generated by Django 3.1.3 on 2020-11-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20201116_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cant_vendida',
            field=models.PositiveIntegerField(),
        ),
    ]
