# Generated by Django 3.1.3 on 2020-11-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20201117_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
