# Generated by Django 3.1.3 on 2020-11-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0002_producto_costo'),
        ('tienda', '0005_venta_procesado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='precio_venta',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cant_vendida',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_vendida', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='id_detalle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.detalle_venta'),
            preserve_default=False,
        ),
    ]
