# Generated by Django 3.1.3 on 2020-11-21 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_auto_20201121_0856'),
        ('tienda', '0006_auto_20201120_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalle Ventas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='procesado',
            new_name='procesada',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_detalle',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='cant_vendida',
            field=models.PositiveIntegerField(verbose_name='Cantidad Vendida'),
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_producto',
            field=models.ManyToManyField(to='productos.Producto'),
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
