# Generated by Django 3.1.3 on 2020-11-21 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0004_auto_20201121_0933'),
        ('tienda', '0007_auto_20201121_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
