# Generated by Django 3.1.3 on 2020-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20201121_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='venta_finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
