# Generated by Django 3.1.3 on 2020-11-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20201129_1234'),
        ('tienda', '0011_auto_20201129_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
    ]
