# Generated by Django 3.1.4 on 2020-12-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_auto_20201201_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='apellido_inv',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_inv',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_inv',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
