# Generated by Django 3.1.3 on 2020-11-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prd', models.CharField(max_length=30, verbose_name='Nombre Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_prd', models.ImageField(blank=True, upload_to='productos')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria_prod', verbose_name='Categoria')),
            ],
        ),
    ]
