# Generated by Django 3.1.3 on 2020-11-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201121_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_prod',
            options={'verbose_name': 'Categoria Producto', 'verbose_name_plural': 'Categoria Productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
